title: Make your own Power Bank
hero_image: images/banner.png
description: generic-electronics-power-bank description
theme:
duration:
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2018-04-10"
curriculum: 
interests:
technologies:
hardware: 
software: 
site_areas: projects
steps:
  - title: Make your own Power Bank

